ERROR: I didn't update npm prior to express generation
I accidently started this repo using an outdated version of
'express-generator'.  This commit deletes EVERYTHING, and starts over
with a fresh call of these two commands:

express -c stylus app
(change to app directory)
npm install

After doing those steps 'npm start' will start the basic express server
on port 3000.

NOW, I will start to show how to create a Sunshine server.